### ISSUE TITLE
'make' fails

### ISSUE THREAD

**Issue by nspark** [USArmyResearchLab/ARL_OpenSHMEM#1]
I get a lot of errors when I try to build ARL OpenSHMEM, but they likely start with the auto-generation of shmem.h:

```
ARL_OpenSHMEM(master)$ make 
make -C src 
make[1]: Entering directory '/dev/shm/ARL_OpenSHMEM/src'
make -C ./autogen
make[2]: Entering directory '/dev/shm/ARL_OpenSHMEM/src/autogen'
./generate.pl
ln -sf ./shmem_api.h ./shmem.h
make build
make[3]: Entering directory '/dev/shm/ARL_OpenSHMEM/src/autogen'
cc -Wall -Wno-unused-function -g -O3  -I..  -c shmem_uint32_atomic_add.c
shmem_uint32_atomic_add.c:1:1: error: expected identifier or ‘(’ before ‘-’ token
    1 | -e
      | ^
In file included from shmem_uint32_atomic_add.c:8:
shmem.h:176:1: error: expected identifier or ‘(’ before ‘-’ token
  176 | -e
      | ^
```

Setup:

- Ubuntu 19.10
- GCC 9.2.1
- perl 5.28.1

**Comment by jamesaross** [comment]
This was a weird bug, but I was able to reproduce it on a similar system.  It's still not clear to me whether perl, the system command, or the echo command is causing the issue.

The perl code was incorrectly outputting "-e" when `echo` should not because it's a command line argument.
```perl
system "echo -e \"msg\""
```
will output `"-e msg"` for some reason.

I believe 1814005 fixes the issue by removing the "-e" from the command and related escape sequences to bypass escape sequences altogether.

**Comment by nspark** [comment]
Thanks! I'm not a Perl person, but I thought this behavior was interesting:

```
$ echo 'system "echo -e foo bar baz"' | perl
foo bar baz
$ echo 'system "echo -e \"foo bar baz\""' | perl
-e foo bar baz
$ echo 'system "echo -e 'foo bar baz'"' | perl
foo bar baz
```

**Comment by jamesaross** [comment]
Thanks for the bug report @nspark.

I would say I dabble in Perl. It was @browndeer who had written the generate.pl script. Perl and other conservative tools were chosen because we had assumed they would provide a stable environment for many years.  Obviously, this assumption may now be challenged.

Since you're here, it also looks like Ubuntu and clones are now substituting bash for dash.  So another environment change which causes problems with oshrun.  The 372727d patch I just pushed addresses that.
